import{describe,expect,it,vi}from"vitest";import{DEFAULT_ACTIVE_PLAYER_CONFIG}from"./ActivePlayerConfig";import{DefaultActivePlayerSession}from"./ActivePlayerSession";import type{PoseDetection}from"./activePlayerTypes";
const config={...DEFAULT_ACTIVE_PLAYER_CONFIG,minimumRegistrationDurationMs:100,temporaryLostGraceMs:100,reidentificationTimeoutMs:200,maximumMissedFrames:1};
describe("DefaultActivePlayerSession",()=>{it("registers the only stable raised-hand candidate among two people",()=>{const session=create();session.beginRegistration(0);session.process([person(.3,0,true),person(.7,1,false)],0);session.process([person(.31,0,true),person(.69,1,false)],110);expect(session.getSnapshot()).toMatchObject({state:"LOCKED",activeTrackId:"track-1",registrationProgress:1});});
it("does not register when multiple people perform the gesture",()=>{const session=create();session.beginRegistration(0);session.process([person(.3,0,true),person(.7,1,true)],0);session.process([person(.3,0,true),person(.7,1,true)],150);expect(session.getSnapshot()).toMatchObject({state:"REGISTERING",activeTrackId:undefined,registrationProgress:0});});
it("reacquires the same track inside grace",()=>{const session=locked();const id=session.getSnapshot().activeTrackId;session.process([],150);expect(session.getSnapshot().state).toBe("TEMPORARILY_LOST");session.process([person(.31,0,false)],200);expect(session.getSnapshot()).toMatchObject({state:"LOCKED",activeTrackId:id});});
it("reidentifies a removed track from the session descriptor",()=>{const session=locked();session.process([],150);session.process([],300);expect(session.getSnapshot().state).toBe("REIDENTIFYING");session.process([person(.31,0,false)],350);expect(session.getSnapshot()).toMatchObject({state:"LOCKED",activeTrackId:"track-2",idSwitchCount:1});});
it("never automatically locks a different remaining person",()=>{const session=locked();session.process([],150);session.process([],300);session.process([person(.75,1,false)],350);expect(session.getSnapshot().state).toBe("REIDENTIFYING");expect(session.getSnapshot().activeTrackId).toBe("track-1");session.process([person(.75,1,false)],560);expect(session.getSnapshot().state).toBe("USER_LOST");});
it("marks similar re-identification candidates ambiguous",()=>{const session=locked();session.process([],150);session.process([],300);session.process([person(.29,0,false),person(.32,0,false)],350);expect(session.getSnapshot().state).toBe("AMBIGUOUS");});
it("supports re-registration and clears descriptors/tracks on dispose",()=>{const session=locked();session.process([],150);session.process([],300);session.process([],550);expect(session.getSnapshot().state).toBe("USER_LOST");session.beginRegistration(600);expect(session.getSnapshot()).toMatchObject({state:"REGISTERING",activeTrackId:undefined});const listener=vi.fn();session.subscribe(listener);session.dispose();expect(session.getSnapshot()).toMatchObject({state:"UNREGISTERED",activeTrackId:undefined,tracks:[]});expect(()=>session.beginRegistration()).toThrow(/disposed/);});});
function create(){let id=0;return new DefaultActivePlayerSession(config,()=>`track-${++id}`);}function locked(){const session=create();session.beginRegistration(0);session.process([person(.3,0,true)],0);session.process([person(.3,0,true)],110);return session;}
function person(centerX:number,variant=0,gesture=false):PoseDetection{const points=Array.from({length:33},()=>({x:centerX,y:.5,z:0,visibility:1}));points[11]={x:centerX-.1,y:.35,z:0,visibility:1};points[12]={x:centerX+.1,y:.35,z:0,visibility:1};points[23]={x:centerX-.08,y:.7,z:0,visibility:1};points[24]={x:centerX+.08,y:.7,z:0,visibility:1};points[13]={x:centerX-.12-.01*variant,y:gesture?.25:.5,z:0,visibility:1};points[14]={x:centerX+.12+.01*variant,y:.5,z:0,visibility:1};points[15]={x:centerX-.13-.02*variant,y:gesture?.12:.62,z:0,visibility:1};points[16]={x:centerX+.13+.02*variant,y:.62,z:0,visibility:1};const histogram=new Float32Array(16);histogram[variant%16]=1;return{boundingBox:{x:Math.max(0,centerX-.18),y:.1,width:.36,height:.7},poseLandmarks:points,torsoColorHistogram:histogram};}
