import {DEFAULT_ACTIVE_PLAYER_CONFIG,type ActivePlayerConfig,validateActivePlayerConfig}from"./ActivePlayerConfig";import{ActivePlayerMatcher}from"./ActivePlayerMatcher";import{ActivePlayerRegistrationController}from"./ActivePlayerRegistrationController";import{ActivePlayerStateMachine}from"./ActivePlayerStateMachine";import{NormalizedPoseFeatureExtractor}from"./PoseFeatureExtractor";import{PersonTrackManager}from"./PersonTrackManager";import type{ActivePlayerMatchScore,ActivePlayerSnapshot,NormalizedBoundingBox,PlayerAppearanceDescriptor,PoseDetection}from"./activePlayerTypes";
export interface ActivePlayerSession {beginRegistration(now?:number):void;cancelRegistration():void;resetRegistration(now?:number):void;clearRegistration():void;process(detections:readonly PoseDetection[],now:number):void;getSnapshot():ActivePlayerSnapshot;getConfig():ActivePlayerConfig;subscribe(listener:(snapshot:ActivePlayerSnapshot)=>void):()=>void;dispose():void;}
export class DefaultActivePlayerSession implements ActivePlayerSession {private readonly machine=new ActivePlayerStateMachine();private readonly manager:PersonTrackManager;private readonly registration=new ActivePlayerRegistrationController();private readonly matcher:ActivePlayerMatcher;private readonly listeners=new Set<(snapshot:ActivePlayerSnapshot)=>void>();private activeTrackId:string|undefined;private descriptor:PlayerAppearanceDescriptor|undefined;private lastBox:NormalizedBoundingBox|undefined;private lostAt:number|undefined;private reidentifyAt:number|undefined;private scores:readonly ActivePlayerMatchScore[]=[];private detected=0;private idSwitchCount=0;private registrationProgress=0;private lastProcessedAt=0;private disposed=false;
 constructor(private readonly config:ActivePlayerConfig=DEFAULT_ACTIVE_PLAYER_CONFIG,createTrackId?:()=>string){validateActivePlayerConfig(config);const extractor=new NormalizedPoseFeatureExtractor();this.manager=new PersonTrackManager({config,featureExtractor:extractor,createTrackId});this.matcher=new ActivePlayerMatcher(config);}
 beginRegistration(now=Date.now()){this.assert();this.machine.transition("REGISTERING");this.lastProcessedAt=now;this.activeTrackId=undefined;this.descriptor=undefined;this.lastBox=undefined;this.lostAt=undefined;this.reidentifyAt=undefined;this.scores=[];this.registrationProgress=0;this.registration.reset();this.publish();}
 cancelRegistration(){this.assert();if(this.machine.getState()==="REGISTERING")this.machine.transition("UNREGISTERED");this.manager.clear();this.activeTrackId=undefined;this.descriptor=undefined;this.registration.reset();this.registrationProgress=0;this.publish();}
 resetRegistration(now=Date.now()){this.assert();if(this.machine.getState()!=="REGISTERING")this.machine.transition("REGISTERING");this.manager.clear();this.activeTrackId=undefined;this.descriptor=undefined;this.lastBox=undefined;this.lostAt=undefined;this.reidentifyAt=undefined;this.scores=[];this.registration.reset();this.registrationProgress=0;this.lastProcessedAt=now;this.publish();}
 clearRegistration(){this.assert();this.manager.clear();this.machine.reset();this.activeTrackId=undefined;this.descriptor=undefined;this.lastBox=undefined;this.lostAt=undefined;this.reidentifyAt=undefined;this.scores=[];this.registration.reset();this.registrationProgress=0;this.publish();}
 process(detections:readonly PoseDetection[],now:number){this.assert();this.lastProcessedAt=now;this.detected=Math.min(detections.length,this.config.maximumTrackedPeople);const tracks=this.manager.update(detections,now),state=this.machine.getState();if(state==="UNREGISTERED"||state==="USER_LOST"){this.publish();return;}if(state==="REGISTERING"){const result=this.registration.update(tracks,now,this.config);this.registrationProgress=result.progress;if(result.trackId){const track=tracks.find((item)=>item.trackId===result.trackId);if(track?.appearanceDescriptor){this.lock(track.trackId,track.appearanceDescriptor,track.boundingBox,false);}}this.publish();return;}
  const active=this.activeTrackId?tracks.find((track)=>track.trackId===this.activeTrackId&&track.state==="ACTIVE"&&track.lastSeenAt===now):undefined;if(active){this.lastBox=active.boundingBox;if(state!=="LOCKED")this.machine.transition("LOCKED");this.lostAt=undefined;this.reidentifyAt=undefined;this.scores=[];this.publish();return;}
  if(state==="LOCKED"){this.machine.transition("TEMPORARILY_LOST");this.lostAt=now;this.publish();return;}if(state==="TEMPORARILY_LOST"&&now-(this.lostAt??now)>this.config.temporaryLostGraceMs){this.machine.transition("REIDENTIFYING");this.reidentifyAt=now;}
  if(this.machine.getState()==="AMBIGUOUS")this.machine.transition("REIDENTIFYING");if(this.machine.getState()==="REIDENTIFYING")this.reidentify(tracks,now);this.publish();}
 getSnapshot():ActivePlayerSnapshot{return{state:this.machine.getState(),activeTrackId:this.activeTrackId,tracks:this.manager.getTracks(),scores:this.scores,detectedPoseCount:this.detected,lostDurationMs:this.lostAt?Math.max(0,this.lastProcessedAt-this.lostAt):0,idSwitchCount:this.idSwitchCount,registrationProgress:this.registrationProgress};}
 getConfig(){return this.config;}
 subscribe(listener:(snapshot:ActivePlayerSnapshot)=>void){this.assert();this.listeners.add(listener);listener(this.getSnapshot());return()=>this.listeners.delete(listener);}
 /** React Fast Refresh가 보존한 Provider 인스턴스만 다시 사용할 수 있게 한다. */
 reactivate(){this.disposed=false;}
 dispose(){if(this.disposed)return;this.disposed=true;this.manager.clear();this.listeners.clear();this.descriptor=undefined;this.activeTrackId=undefined;this.lastBox=undefined;this.lostAt=undefined;this.reidentifyAt=undefined;this.scores=[];this.registration.reset();this.registrationProgress=0;this.machine.reset();}
 private reidentify(tracks:ReturnType<PersonTrackManager["getTracks"]>,now:number){if(!this.descriptor){this.machine.transition("USER_LOST");return;}this.scores=this.matcher.rank(this.descriptor,this.lastBox,tracks);const best=this.scores[0];if(best&&best.totalScore>=this.config.minimumLockScore){if(this.matcher.isAmbiguous(this.scores)){this.machine.transition("AMBIGUOUS");return;}const track=tracks.find((item)=>item.trackId===best.trackId);if(track){this.lock(track.trackId,this.descriptor,track.boundingBox,true);return;}}if(now-(this.reidentifyAt??now)>this.config.reidentificationTimeoutMs)this.machine.transition("USER_LOST");}
 private lock(trackId:string,descriptor:PlayerAppearanceDescriptor,box:NormalizedBoundingBox,idSwitch:boolean){if(idSwitch&&this.activeTrackId&&this.activeTrackId!==trackId)this.idSwitchCount+=1;this.activeTrackId=trackId;this.descriptor={...descriptor,torsoColorHistogram:new Float32Array(descriptor.torsoColorHistogram),poseProportions:new Float32Array(descriptor.poseProportions)};this.lastBox={...box};this.lostAt=undefined;this.reidentifyAt=undefined;this.registrationProgress=1;this.machine.transition("LOCKED");}
 private publish(){const snapshot=this.getSnapshot();this.listeners.forEach((listener)=>listener(snapshot));}private assert(){if(this.disposed)throw new Error("Active player session is disposed.");}}
