import type { ActivePlayerConfig } from "./ActivePlayerConfig";
import { PersonDetectionMatcher, predict } from "./PersonDetectionMatcher";
import type { PoseFeatureExtractor } from "./PoseFeatureExtractor";
import type { NormalizedBoundingBox, PersonTrack, PlayerAppearanceDescriptor, PoseDetection } from "./activePlayerTypes";

export interface PersonTrackManagerOptions { readonly config:ActivePlayerConfig;readonly featureExtractor:PoseFeatureExtractor;readonly createTrackId?:()=>string; }
export class PersonTrackManager {
  private tracks:PersonTrack[]=[];private readonly matcher:PersonDetectionMatcher;private readonly createTrackId:()=>string;
  constructor(private readonly options:PersonTrackManagerOptions){this.matcher=new PersonDetectionMatcher(options.featureExtractor,options.config);this.createTrackId=options.createTrackId??(()=>crypto.randomUUID());}
  update(input:readonly PoseDetection[],now:number):readonly PersonTrack[]{const detections=input.slice(0,this.options.config.maximumTrackedPeople);const live=this.tracks.filter((track)=>track.state!=="REMOVED");const matches=this.matcher.match(live,detections,now);const matchedTracks=new Set(matches.map((item)=>item.trackIndex)),matchedDetections=new Set(matches.map((item)=>item.detectionIndex));
    const updated:PersonTrack[]=live.map((track,index)=>{const match=matches.find((item)=>item.trackIndex===index);if(!match){const missed=track.missedFrames+1;return{...track,predictedBoundingBox:predict(track,now),missedFrames:missed,state:missed>this.options.config.maximumMissedFrames?"REMOVED":"LOST"};}return this.updateTrack(track,detections[match.detectionIndex]!,now);});
    for(let index=0;index<detections.length&&updated.filter((track)=>track.state!=="REMOVED").length<this.options.config.maximumTrackedPeople;index+=1){if(!matchedDetections.has(index))updated.push(this.createTrack(detections[index]!,now));}
    void matchedTracks;this.tracks=updated;return this.getTracks();}
  getTracks():readonly PersonTrack[]{return this.tracks.filter((track)=>track.state!=="REMOVED").map(cloneTrack);}
  getTrack(id:string):PersonTrack|undefined{return this.getTracks().find((track)=>track.trackId===id);}
  clear():void{this.tracks=[];}
  private createTrack(detection:PoseDetection,now:number):PersonTrack{const features=this.options.featureExtractor.extract(detection.poseLandmarks);return{trackId:this.createTrackId(),boundingBox:detection.boundingBox,predictedBoundingBox:detection.boundingBox,poseLandmarks:detection.poseLandmarks.map((point)=>({...point})),poseFeatures:features,velocity:{x:0,y:0},appearanceDescriptor:descriptor(detection,features,now),createdAt:now,lastSeenAt:now,missedFrames:0,state:"ACTIVE"};}
  private updateTrack(track:PersonTrack,detection:PoseDetection,now:number):PersonTrack{const before=center(track.boundingBox),after=center(detection.boundingBox),dt=Math.max(1,now-track.lastSeenAt),features=this.options.featureExtractor.extract(detection.poseLandmarks);const velocity={x:(after.x-before.x)/dt,y:(after.y-before.y)/dt};return{...track,boundingBox:detection.boundingBox,predictedBoundingBox:detection.boundingBox,poseLandmarks:detection.poseLandmarks.map((point)=>({...point})),poseFeatures:features,velocity,appearanceDescriptor:descriptor(detection,features,now)??track.appearanceDescriptor,lastSeenAt:now,missedFrames:0,state:"ACTIVE"};}
}
function descriptor(detection:PoseDetection,features:Float32Array,now:number):PlayerAppearanceDescriptor{const shoulders=distance(detection.poseLandmarks[11],detection.poseLandmarks[12]),hips=distance(detection.poseLandmarks[23],detection.poseLandmarks[24]),height=distance(midpoint(detection.poseLandmarks[11],detection.poseLandmarks[12]),midpoint(detection.poseLandmarks[23],detection.poseLandmarks[24]));return{torsoColorHistogram:detection.torsoColorHistogram?new Float32Array(detection.torsoColorHistogram):new Float32Array(16),poseProportions:new Float32Array(features),torsoAspectRatio:height?shoulders/height:0,shoulderWidthRatio:hips?shoulders/hips:0,capturedAt:now};}
function center(box:NormalizedBoundingBox){return{x:box.x+box.width/2,y:box.y+box.height/2};}function cloneTrack(track:PersonTrack):PersonTrack{return{...track,boundingBox:{...track.boundingBox},predictedBoundingBox:{...track.predictedBoundingBox},poseLandmarks:track.poseLandmarks.map((point)=>({...point})),poseFeatures:new Float32Array(track.poseFeatures),velocity:{...track.velocity},appearanceDescriptor:track.appearanceDescriptor?{...track.appearanceDescriptor,torsoColorHistogram:new Float32Array(track.appearanceDescriptor.torsoColorHistogram),poseProportions:new Float32Array(track.appearanceDescriptor.poseProportions)}:undefined};}
function distance(a?:{x:number;y:number;z:number},b?:{x:number;y:number;z:number}){return a&&b?Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z):0;}function midpoint(a?:{x:number;y:number;z:number},b?:{x:number;y:number;z:number}){return a&&b?{x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:(a.z+b.z)/2}:undefined;}
