import { describe, expect, it, vi } from "vitest";
import type { SharedGameCameraSession } from "../../media/camera/SharedGameCameraSession";
import type { ActivePlayerSession, ActivePlayerSnapshot, HandCandidate } from "../active-player";
import { RecognitionPerformanceMonitor } from "../runtime";
import type { SignRecognitionEvent } from "../types/events";
import type { PythonWebSocketSignRecognizer } from "../websocket/PythonWebSocketSignRecognizer";
import { DEFAULT_GAME_RECOGNITION_OPTIONS, DefaultGameRecognitionSession } from "./DefaultGameRecognitionSession";

describe("DefaultGameRecognitionSession",()=>{
  /**
   * 활성 플레이어 락은 88a01df에서 게임 경로에서 비활성화됐다(디버그 도구로만 유지).
   * 그래서 기본 옵션으로 시작하면 등록 절차를 밟지 않는다. 락을 켠 경로는 아래에서 따로 본다.
   */
  it("starts the shared camera without registering a player or taking camera cleanup ownership",async()=>{const camera=fakeCamera(),player=fakePlayer(),recognizer=fakeRecognizer();const session=new DefaultGameRecognitionSession(recognizer.value,player.value);await session.start(DEFAULT_GAME_RECOGNITION_OPTIONS(camera.value));expect(camera.start).toHaveBeenCalledOnce();expect(recognizer.connect).toHaveBeenCalledOnce();expect(player.begin).not.toHaveBeenCalled();expect(session.getSnapshot().connectionState).toBe("READY");await session.stop();expect(camera.stop).not.toHaveBeenCalled();expect(recognizer.disconnect).toHaveBeenCalledOnce();});
  it("accepts a single hand without a player lock under the shipped defaults",async()=>{const camera=fakeCamera(),player=fakePlayer(),recognizer=fakeRecognizer(),session=new DefaultGameRecognitionSession(recognizer.value,player.value);await session.start(DEFAULT_GAME_RECOGNITION_OPTIONS(camera.value));const result=session.resolveHandCandidates([hand()],100);expect(result.inputAllowed).toBe(true);expect(result.selected?.detectionId).toBe("hand");expect(session.getSnapshot().blockReason).toBeUndefined();});
  it("blocks hand input while an active player is not locked once the lock is required",async()=>{const camera=fakeCamera(),player=fakePlayer(),recognizer=fakeRecognizer(),session=new DefaultGameRecognitionSession(recognizer.value,player.value);await session.start({...DEFAULT_GAME_RECOGNITION_OPTIONS(camera.value),requireActivePlayerLock:true,safetyMode:"ACTIVE_PLAYER_REQUIRED"});expect(player.begin).toHaveBeenCalledOnce();const result=session.resolveHandCandidates([hand()],100);expect(result.inputAllowed).toBe(false);expect(session.getSnapshot().blockReason).toBe("ACTIVE_PLAYER_NOT_REGISTERED");});
  it("allows only explicit single-person fallback in development mode",async()=>{const camera=fakeCamera(),player=fakePlayer(),recognizer=fakeRecognizer(),session=new DefaultGameRecognitionSession(recognizer.value,player.value);await session.start({...DEFAULT_GAME_RECOGNITION_OPTIONS(camera.value),requireActivePlayerLock:false,allowFallbackSingleHandMode:true,safetyMode:"SINGLE_PERSON_FALLBACK"});expect(session.resolveHandCandidates([hand()],100).inputAllowed).toBe(true);expect(session.resolveHandCandidates([hand("a"),hand("b")],120).inputAllowed).toBe(false);});
  it("forwards the selected landmark only through the existing recognizer contract",async()=>{const camera=fakeCamera(),player=fakePlayer(),recognizer=fakeRecognizer(),session=new DefaultGameRecognitionSession(recognizer.value,player.value);await session.start({...DEFAULT_GAME_RECOGNITION_OPTIONS(camera.value),requireActivePlayerLock:false,allowFallbackSingleHandMode:true,safetyMode:"SINGLE_PERSON_FALLBACK"});const selected=session.resolveHandCandidates([hand()],100);session.submitLandmarkFrame({frameId:1,capturedAt:100,handedness:"RIGHT",landmarks:hand().landmarks,activeHandId:selected.activeHandId,activeHandSessionId:selected.sessionId});expect(recognizer.send).toHaveBeenCalledWith(expect.objectContaining({frameId:1,activeHandId:selected.activeHandId}));});
  it("publishes only final confirmation as the shared game input event",async()=>{const camera=fakeCamera(),player=fakePlayer(),recognizer=fakeRecognizer(),session=new DefaultGameRecognitionSession(recognizer.value,player.value),events:string[]=[];session.subscribe((event)=>events.push(event.type));await session.start({...DEFAULT_GAME_RECOGNITION_OPTIONS(camera.value),requireActivePlayerLock:false,safetyMode:"LEGACY_HAND_ONLY"});recognizer.emit({type:"PREDICTION",frameId:1,symbol:"ㄱ",confidence:.9,isStable:false,predictedAt:100});recognizer.emit({type:"SIGN_CONFIRMED",symbol:"ㄱ",confidence:.9,confirmedAt:120,modelVersion:"test"});expect(events.filter((type)=>type==="SIGN_CONFIRMED")).toHaveLength(1);});
});
function fakeCamera(){const stream={} as MediaStream;let current:MediaStream|null=null;const start=vi.fn(async()=>{current=stream;return stream;}),stop=vi.fn(()=>{current=null;});return{start,stop,value:{start,getStream:()=>current,getVideoTrack:()=>null,stop} satisfies SharedGameCameraSession};}
function fakePlayer(){let snapshot:ActivePlayerSnapshot={state:"UNREGISTERED",tracks:[],scores:[],detectedPoseCount:0,lostDurationMs:0,idSwitchCount:0,registrationProgress:0};const listeners=new Set<(value:ActivePlayerSnapshot)=>void>(),begin=vi.fn(()=>{snapshot={...snapshot,state:"REGISTERING"};listeners.forEach((listener)=>listener(snapshot));});const clear=()=>{snapshot={...snapshot,state:"UNREGISTERED"};};const value:ActivePlayerSession={beginRegistration:begin,cancelRegistration:clear,resetRegistration:begin,clearRegistration:clear,process:()=>undefined,getSnapshot:()=>snapshot,getConfig:()=>DEFAULT_GAME_RECOGNITION_OPTIONS({} as SharedGameCameraSession).activePlayerConfig,subscribe:(listener)=>{listeners.add(listener);listener(snapshot);return()=>listeners.delete(listener);},dispose:()=>undefined};return{begin,value};}
function fakeRecognizer(){let state:"DISCONNECTED"|"CONNECTED"="DISCONNECTED";const listeners=new Set<(event:SignRecognitionEvent)=>void>(),monitor=new RecognitionPerformanceMonitor(),connect=vi.fn(async()=>{state="CONNECTED";}),disconnect=vi.fn(()=>{state="DISCONNECTED";}),send=vi.fn();const decoder={getSnapshot:()=>({state:"NO_HAND",motion:{averageVelocity:0,maximumVelocity:0,wristVelocity:0,fingerVelocity:0,stableDurationMs:0,moving:false},candidateVotes:0,releasePoseDistance:0,averageConfirmationLatencyMs:0,p95ConfirmationLatencyMs:0,confirmations:0,droppedPredictions:0,stalePredictions:0}),getConfig:()=>DEFAULT_GAME_RECOGNITION_OPTIONS({} as SharedGameCameraSession).decoderConfig,updateConfig:()=>undefined};const value={connect,disconnect,configureHardening:vi.fn(),subscribe:(listener:(event:SignRecognitionEvent)=>void)=>{listeners.add(listener);return()=>listeners.delete(listener);},getConnectionState:()=>state,getTemporalDecoder:()=>decoder,getPerformanceMonitor:()=>monitor,sendLandmarkFrame:send,notifyHandNotDetected:vi.fn()} as unknown as PythonWebSocketSignRecognizer;return{value,connect,disconnect,send,emit:(event:SignRecognitionEvent)=>listeners.forEach((listener)=>listener(event))};}
function hand(id="hand"):HandCandidate{return{detectionId:id,handedness:"RIGHT",handednessScore:1,wrist:{x:.5,y:.5,z:0},landmarks:Array.from({length:21},()=>({x:.5,y:.5,z:0})),detectedAt:100};}
