import { ActiveHandTracker, DefaultActivePlayerSession, HandOwnerResolver, type ActivePlayerSession, type HandCandidate, type PoseDetection } from "../active-player";
import { DEFAULT_RECOGNITION_RATE_CONFIG, type RecognitionPerformanceSnapshot } from "../runtime";
import { DEFAULT_SIGN_DECODER_CONFIG } from "../temporal";
import type { SignRecognitionEvent } from "../types/events";
import type { HandLandmarkFrame } from "../types/landmark";
import { DEFAULT_ACTIVE_PLAYER_CONFIG } from "../active-player/ActivePlayerConfig";
import { DEFAULT_HAND_OWNERSHIP_CONFIG } from "../active-player/handOwnershipTypes";
import { DEFAULT_RECOGNITION_HARDENING_FLAGS, type GameRecognitionBackend, type GameRecognitionEvent, type GameRecognitionPipelineAdapter, type GameRecognitionSessionOptions, type GameRecognitionSnapshot, type RecognitionInputBlockReason, type RecognitionSafetyMode } from "./GameRecognitionSession";

const EMPTY_PERFORMANCE:RecognitionPerformanceSnapshot={cameraFps:0,renderFps:0,handTrackingFps:0,poseTrackingFps:0,aiRequestFps:0,aiResponseFps:0,aiAverageLatencyMs:0,aiP95LatencyMs:0,handAverageLatencyMs:0,handP95LatencyMs:0,droppedHandFrames:0,droppedPoseFrames:0,droppedInferenceFrames:0,staleResponsesIgnored:0,mainThreadLongTaskCount:0,latestUpdatedAt:0};
// Registration and person-ownership locks are not part of gameplay. The first
// visible hand is used directly so a failed sign can be retried immediately.
export const DEFAULT_GAME_RECOGNITION_OPTIONS=(cameraSession:GameRecognitionSessionOptions["cameraSession"]):GameRecognitionSessionOptions=>({cameraSession,requireActivePlayerLock:false,allowFallbackSingleHandMode:true,rateConfig:DEFAULT_RECOGNITION_RATE_CONFIG,decoderConfig:DEFAULT_SIGN_DECODER_CONFIG,activePlayerConfig:DEFAULT_ACTIVE_PLAYER_CONFIG,handOwnershipConfig:DEFAULT_HAND_OWNERSHIP_CONFIG,safetyMode:"LEGACY_HAND_ONLY",featureFlags:DEFAULT_RECOGNITION_HARDENING_FLAGS});

export class DefaultGameRecognitionSession implements GameRecognitionPipelineAdapter{
 private options:GameRecognitionSessionOptions|undefined;private activeHand:ActiveHandTracker|undefined;private connectionState:GameRecognitionSnapshot["connectionState"]="IDLE";private failure:string|undefined;private listeners=new Set<(event:GameRecognitionEvent)=>void>();private unsubs:(()=>void)[]=[];private stream:MediaStream|null=null;private disposed=false;private candidateSymbol:string|undefined;private confirmedSymbol:string|undefined;private confidence:number|undefined;private fallbackSession:{sessionId:string;handId:string}|undefined;
 constructor(private readonly recognizer:GameRecognitionBackend,private readonly activePlayer:ActivePlayerSession=new DefaultActivePlayerSession()){}
 async start(options:GameRecognitionSessionOptions):Promise<void>{if(this.disposed)throw new Error("Recognition session is disposed.");if(this.connectionState==="READY")return;this.options=options;this.recognizer.configureHardening(options.featureFlags??DEFAULT_RECOGNITION_HARDENING_FLAGS);this.failure=undefined;this.connectionState="STARTING";this.activeHand=new ActiveHandTracker(new HandOwnerResolver(options.handOwnershipConfig),options.handOwnershipConfig);this.bind();this.publish();try{this.stream=options.cameraSession.getStream()??await options.cameraSession.start();await this.recognizer.connect();if(options.requireActivePlayerLock&&options.featureFlags?.activePlayerLockEnabled!==false&&this.activePlayer.getSnapshot().state==="UNREGISTERED")this.activePlayer.beginRegistration();this.connectionState="READY";}catch(cause){this.connectionState="FAILED";this.failure=cause instanceof DOMException&&cause.name==="NotAllowedError"?"카메라 권한이 거절되었습니다.":cause instanceof Error?cause.message:"인식 세션을 시작하지 못했습니다.";this.publish();throw cause;}this.publish();}
 beginPlayerRegistration():void{this.activePlayer.beginRegistration();this.activeHand?.reset();this.publish();}
 cancelPlayerRegistration():void{this.activePlayer.cancelRegistration();this.activeHand?.reset();this.publish();}
 resetPlayerRegistration():void{this.activePlayer.resetRegistration();this.activeHand?.reset();this.publish();}
 getSnapshot():GameRecognitionSnapshot{const player=this.activePlayer.getSnapshot(),hand=this.activeHand?.getSnapshot(),decoder=this.recognizer.getTemporalDecoder().getSnapshot(),safety=this.safetyMode(),block=this.blockReason(player.state,hand?.inputAllowed??false,decoder.state);return{connectionState:this.connectionState,error:this.failure,activePlayerState:player.state,activePlayerTrackId:player.activeTrackId,detectedPoseCount:player.detectedPoseCount,registrationProgress:player.registrationProgress,activeHandId:hand?.activeTrack?.handId??this.fallbackSession?.handId,activeHandSessionId:hand?.session?.sessionId??this.fallbackSession?.sessionId,handOwnershipConfidence:hand?.activeTrack?.ownershipConfidence,decoderState:decoder.state,candidateSymbol:this.candidateSymbol??decoder.candidateSymbol,confirmedSymbol:this.confirmedSymbol,confidence:this.confidence,inputAllowed:!block,blockReason:block,safetyMode:safety,performance:this.recognizer.getPerformanceMonitor().getSnapshot()??EMPTY_PERFORMANCE};}
 subscribe(listener:(event:GameRecognitionEvent)=>void):()=>void{this.listeners.add(listener);listener({type:"SNAPSHOT_UPDATED",snapshot:this.getSnapshot()});return()=>this.listeners.delete(listener);}
 async stop():Promise<void>{if(this.connectionState==="CLOSED"||this.connectionState==="IDLE")return;this.unbind();this.recognizer.disconnect();this.activeHand?.reset();this.connectionState="IDLE";this.publish();}
 async dispose():Promise<void>{if(this.disposed)return;await this.stop();this.disposed=true;this.activeHand?.dispose();this.activeHand=undefined;this.fallbackSession=undefined;this.listeners.clear();this.connectionState="CLOSED";}
 getCameraStream():MediaStream|null{return this.stream??this.options?.cameraSession.getStream()??null;}getRateConfig(){return this.options?.rateConfig??DEFAULT_RECOGNITION_RATE_CONFIG;}getMaximumTrackedPeople():number{return this.options?.activePlayerConfig.maximumTrackedPeople??4;}
 getActivePlayerSession():ActivePlayerSession{return this.activePlayer;}
 processPoseDetections(detections:readonly PoseDetection[],capturedAt:number):void{if(this.options?.featureFlags?.activePlayerLockEnabled!==false)this.activePlayer.process(detections,capturedAt);this.publish();}
 resolveHandCandidates(candidates:readonly HandCandidate[],capturedAt:number){const options=this.options;if(!options)return{inputAllowed:false};const lockEnabled=options.featureFlags?.activePlayerLockEnabled!==false&&options.requireActivePlayerLock;if(lockEnabled){const result=this.activeHand?.update(candidates,this.activePlayer.getSnapshot(),capturedAt);this.publish();return{selected:result?.selected,inputAllowed:result?.inputAllowed??false,sessionId:result?.session?.sessionId,activeHandId:result?.session?.activeHandId,ownership:result};}const mode=this.safetyMode(),selected=mode==="LEGACY_HAND_ONLY"?candidates[0]:mode==="SINGLE_PERSON_FALLBACK"&&options.allowFallbackSingleHandMode&&candidates.length===1?candidates[0]:undefined;if(selected&&!this.fallbackSession)this.fallbackSession={sessionId:id(),handId:id()};if(!selected)this.fallbackSession=undefined;this.publish();return{selected,inputAllowed:!!selected,sessionId:this.fallbackSession?.sessionId,activeHandId:this.fallbackSession?.handId};}
 submitLandmarkFrame(frame:HandLandmarkFrame):void{this.recognizer.sendLandmarkFrame(frame);this.publish();}notifyHandNotDetected(capturedAt:number):void{if(this.activeHand?.getSnapshot().activeTrack){this.publish();return;}this.recognizer.notifyHandNotDetected(capturedAt);this.publish();}
 private bind(){if(this.unsubs.length)return;this.unsubs.push(this.recognizer.subscribe((event)=>this.onRecognition(event)),this.activePlayer.subscribe(()=>this.publish()),this.recognizer.getPerformanceMonitor().subscribe(()=>this.publish()));}
 private unbind(){this.unsubs.splice(0).forEach((unsubscribe)=>unsubscribe());}
 private onRecognition(event:SignRecognitionEvent){if(event.type==="PREDICTION"){this.candidateSymbol=event.symbol;this.confidence=event.confidence;}else if(event.type==="SIGN_CONFIRMED"){const lockRequired=this.options?.requireActivePlayerLock&&this.options.featureFlags?.activePlayerLockEnabled!==false,handAllowed=!lockRequired||this.activeHand?.getSnapshot().inputAllowed===true;if(handAllowed){this.confirmedSymbol=event.symbol;this.confidence=event.confidence;this.emit({type:"SIGN_CONFIRMED",symbol:event.symbol,confidence:event.confidence,confirmationLatencyMs:this.recognizer.getTemporalDecoder().getSnapshot().lastConfirmationLatencyMs,occurredAt:event.confirmedAt});}}else if(event.type==="HAND_RELEASED")this.emit({type:"HAND_RELEASED",occurredAt:event.releasedAt});this.publish();}
 private blockReason(player:GameRecognitionSnapshot["activePlayerState"],handAllowed:boolean,decoder:GameRecognitionSnapshot["decoderState"]):RecognitionInputBlockReason|undefined{if(this.connectionState!=="READY")return"CAMERA_NOT_READY";if(this.recognizer.getConnectionState()!=="CONNECTED")return"AI_DISCONNECTED";if(this.options?.requireActivePlayerLock&&this.options.featureFlags?.activePlayerLockEnabled!==false){if(player==="AMBIGUOUS")return"ACTIVE_PLAYER_AMBIGUOUS";if(player==="TEMPORARILY_LOST"||player==="REIDENTIFYING"||player==="USER_LOST")return"ACTIVE_PLAYER_LOST";if(player!=="LOCKED")return"ACTIVE_PLAYER_NOT_REGISTERED";if(!handAllowed)return"HAND_OWNER_UNCERTAIN";}if(decoder==="MOVING")return"HAND_MOVING";if(decoder==="RELEASE_WAIT")return"RELEASE_REQUIRED";return undefined;}
 private safetyMode():RecognitionSafetyMode{return this.options?.safetyMode??"ACTIVE_PLAYER_REQUIRED";}private publish(){if(!this.options&&this.connectionState==="IDLE")return;this.emit({type:"SNAPSHOT_UPDATED",snapshot:this.getSnapshot()});}private emit(event:GameRecognitionEvent){this.listeners.forEach((listener)=>listener(event));}
}
function id(){return globalThis.crypto?.randomUUID?.()??`recognition-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
