import type { SharedGameCameraSession } from "../../media/camera/SharedGameCameraSession";
import type { ActiveHandSnapshot, ActivePlayerConfig, ActivePlayerState, HandCandidate, HandOwnershipConfig, PoseDetection } from "../active-player";
import type { SignRecognizer } from "../core/SignRecognizer";
import type { RecognitionPerformanceMonitor, RecognitionPerformanceSnapshot, RecognitionRateConfig } from "../runtime";
import type { ContinuousSignRecognizer, DefaultContinuousSignDecoder, SignDecoderConfig, SignDecoderState } from "../temporal";
import type { HandLandmarkFrame } from "../types/landmark";

export type GameRecognitionConnectionState="IDLE"|"STARTING"|"READY"|"FAILED"|"CLOSED";
export type RecognitionInputBlockReason="CAMERA_NOT_READY"|"ACTIVE_PLAYER_NOT_REGISTERED"|"ACTIVE_PLAYER_LOST"|"ACTIVE_PLAYER_AMBIGUOUS"|"HAND_OWNER_UNCERTAIN"|"HAND_MOVING"|"AI_DISCONNECTED"|"LOW_CONFIDENCE"|"RELEASE_REQUIRED";
export type RecognitionSafetyMode="ACTIVE_PLAYER_REQUIRED"|"SINGLE_PERSON_FALLBACK"|"LEGACY_HAND_ONLY";
export interface RecognitionHardeningFeatureFlags { readonly latestOnlyInferenceEnabled:boolean;readonly continuousSignDecoderEnabled:boolean;readonly activePlayerLockEnabled:boolean;readonly segmentationAssistEnabled:boolean;readonly personReIdentificationEnabled:boolean;readonly recognitionDebugEnabled:boolean; }
export const DEFAULT_RECOGNITION_HARDENING_FLAGS:RecognitionHardeningFeatureFlags=Object.freeze({latestOnlyInferenceEnabled:true,continuousSignDecoderEnabled:true,activePlayerLockEnabled:true,segmentationAssistEnabled:false,personReIdentificationEnabled:false,recognitionDebugEnabled:import.meta.env.DEV});
export interface GameRecognitionSessionOptions { readonly cameraSession:SharedGameCameraSession;readonly requireActivePlayerLock:boolean;readonly allowFallbackSingleHandMode:boolean;readonly rateConfig:RecognitionRateConfig;readonly decoderConfig:SignDecoderConfig;readonly activePlayerConfig:ActivePlayerConfig;readonly handOwnershipConfig:HandOwnershipConfig;readonly safetyMode?:RecognitionSafetyMode;readonly featureFlags?:RecognitionHardeningFeatureFlags; }
/** Recognition backend port. The current WebSocket adapter and future local implementations share this boundary. */
export interface GameRecognitionBackend extends SignRecognizer { configureHardening(flags:RecognitionHardeningFeatureFlags):void;sendLandmarkFrame(frame:HandLandmarkFrame):void;notifyHandNotDetected(capturedAt:number):void;getTemporalDecoder():ContinuousSignRecognizer&Pick<DefaultContinuousSignDecoder,"getConfig"|"updateConfig">;getPerformanceMonitor():RecognitionPerformanceMonitor; }
export interface GameRecognitionSnapshot { readonly connectionState:GameRecognitionConnectionState;readonly error?:string;readonly activePlayerState:ActivePlayerState;readonly activePlayerTrackId?:string;readonly detectedPoseCount:number;readonly registrationProgress:number;readonly activeHandId?:string;readonly activeHandSessionId?:string;readonly handOwnershipConfidence?:number;readonly decoderState:SignDecoderState;readonly candidateSymbol?:string;readonly confirmedSymbol?:string;readonly confidence?:number;readonly inputAllowed:boolean;readonly blockReason?:RecognitionInputBlockReason;readonly safetyMode:RecognitionSafetyMode;readonly performance:RecognitionPerformanceSnapshot; }
export type GameRecognitionEvent={readonly type:"SNAPSHOT_UPDATED";readonly snapshot:GameRecognitionSnapshot}|{readonly type:"SIGN_CONFIRMED";readonly symbol:string;readonly confidence:number;readonly confirmationLatencyMs?:number;readonly occurredAt:number}|{readonly type:"HAND_RELEASED";readonly occurredAt:number};
export interface GameRecognitionSession { start(options:GameRecognitionSessionOptions):Promise<void>;beginPlayerRegistration():void;cancelPlayerRegistration():void;resetPlayerRegistration():void;getSnapshot():GameRecognitionSnapshot;subscribe(listener:(event:GameRecognitionEvent)=>void):()=>void;stop():Promise<void>;dispose():Promise<void>; }
export interface GameRecognitionPipelineAdapter extends GameRecognitionSession { getCameraStream():MediaStream|null;getRateConfig():RecognitionRateConfig;getMaximumTrackedPeople():number;getActivePlayerSession():import("../active-player").ActivePlayerSession;processPoseDetections(detections:readonly PoseDetection[],capturedAt:number):void;resolveHandCandidates(candidates:readonly HandCandidate[],capturedAt:number):{readonly selected?:HandCandidate;readonly inputAllowed:boolean;readonly sessionId?:string;readonly activeHandId?:string;readonly ownership?:ActiveHandSnapshot};submitLandmarkFrame(frame:HandLandmarkFrame):void;notifyHandNotDetected(capturedAt:number):void; }
