# STUN/TURN 기본 포트
listening-port=3478

# WebRTC 요청 식별
fingerprint

# 사용자명/비밀번호 인증 사용
lt-cred-mech

# TURN 서버 식별 도메인
realm=i15a405.p.ssafy.io
server-name=i15a405.p.ssafy.io

# 미디어 릴레이 UDP 포트 범위
min-port=49160
max-port=49200

# 보안 설정
stale-nonce=600
no-multicast-peers

# 로그를 Docker 로그로 출력
log-file=stdout
simple-log

# TLS는 Jira 589에서 별도로 적용
no-tls
no-dtls