{
 "title": "Sudal Infrastructure Overview",
 "time": { "from": "2026-08-11T15:53:26.062Z", "to": "2026-08-12T15:53:26.062Z" },
 "panels": [
  {
   "title": "EC2 CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  node_filesystem_avail_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"}\r\n  /\r\n  node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\r\n  rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bytes (IEC)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\r\n  container_memory_working_set_bytes{name!=\"\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}