import { useEffect, useState } from "react";
import type { GameRecognitionSession, GameRecognitionSnapshot } from "../session";

const blockMessages:Record<NonNullable<GameRecognitionSnapshot["blockReason"]>,string>={CAMERA_NOT_READY:"카메라를 준비하고 있습니다.",ACTIVE_PLAYER_NOT_REGISTERED:"게임 사용자를 등록해 주세요.",ACTIVE_PLAYER_LOST:"등록 사용자를 다시 찾고 있습니다.",ACTIVE_PLAYER_AMBIGUOUS:"사용자 식별이 불확실합니다.",HAND_OWNER_UNCERTAIN:"등록한 사용자의 손을 확인하고 있습니다.",HAND_MOVING:"손을 안정적으로 유지해 주세요.",AI_DISCONNECTED:"AI 연결이 끊겼습니다.",LOW_CONFIDENCE:"지문자를 조금 더 정확히 보여 주세요.",RELEASE_REQUIRED:"다음 입력을 위해 손 자세를 바꿔 주세요."};
export function useGameRecognitionSnapshot(session:GameRecognitionSession){const[snapshot,setSnapshot]=useState(()=>session.getSnapshot());useEffect(()=>session.subscribe((event)=>{if(event.type==="SNAPSHOT_UPDATED")setSnapshot(event.snapshot);}),[session]);return snapshot;}
export function ActivePlayerRegistrationModal({session}:{readonly session:GameRecognitionSession}){const snapshot=useGameRecognitionSnapshot(session);if(!["UNREGISTERED","REGISTERING","USER_LOST"].includes(snapshot.activePlayerState))return null;const registering=snapshot.activePlayerState==="REGISTERING",percent=Math.round(snapshot.registrationProgress*100);return <div className="recognition-registration" role="dialog" aria-label="게임 사용자 등록"><strong>{registering?"게임 참가자 등록 중":"게임 참가자를 등록합니다."}</strong><span>상반신 전체가 보이게 서서 한쪽 손을 머리 위로 들어 주세요.</span>{registering&&<><span aria-live="polite">{snapshot.detectedPoseCount>0?`사람 ${snapshot.detectedPoseCount}명 감지 · 등록 ${percent}%`:"사람을 찾는 중 · 카메라에서 조금 뒤로 이동해 주세요."}</span><progress max={1} value={snapshot.registrationProgress}/><small>100%가 되면 자동으로 등록이 완료됩니다.</small></>}{registering?<button type="button" onClick={()=>session.cancelPlayerRegistration()}>취소</button>:<button type="button" onClick={()=>session.beginPlayerRegistration()}>사용자 등록</button>}</div>}
export function ActivePlayerStatusBadge({session}:{readonly session:GameRecognitionSession}){const snapshot=useGameRecognitionSnapshot(session);return <span className={`recognition-status-badge state-${snapshot.activePlayerState.toLowerCase()}`}>{snapshot.activePlayerState==="LOCKED"?"사용자 인식 완료":snapshot.activePlayerState}</span>}
export function RecognitionInputStatus({session}:{readonly session:GameRecognitionSession}){const snapshot=useGameRecognitionSnapshot(session);return <div className="recognition-input-status" role="status"><strong>{snapshot.inputAllowed?"지문자 입력 가능":"지문자 입력 잠금"}</strong><span>{snapshot.confirmedSymbol?`인식 완료: ${snapshot.confirmedSymbol}`:snapshot.candidateSymbol?`인식 중: ${snapshot.candidateSymbol}`:"입력 대기"}</span></div>}
export function RecognitionBlockedOverlay({session}:{readonly session:GameRecognitionSession}){const snapshot=useGameRecognitionSnapshot(session);const transient=snapshot.blockReason==="HAND_MOVING"||snapshot.blockReason==="LOW_CONFIDENCE"||snapshot.blockReason==="RELEASE_REQUIRED";if(snapshot.inputAllowed||transient)return null;return <div className="recognition-blocked-overlay" role="status">{snapshot.blockReason?blockMessages[snapshot.blockReason]:"입력을 확인하고 있습니다."}</div>}
export function RecognitionDebugOverlay({session}:{readonly session:GameRecognitionSession}){const snapshot=useGameRecognitionSnapshot(session);if(!import.meta.env.DEV)return null;return <pre className="recognition-debug-overlay">{JSON.stringify({connection:snapshot.connectionState,player:snapshot.activePlayerState,playerId:snapshot.activePlayerTrackId,handId:snapshot.activeHandId,ownership:snapshot.handOwnershipConfidence,decoder:snapshot.decoderState,inputAllowed:snapshot.inputAllowed,blocked:snapshot.blockReason,safety:snapshot.safetyMode},null,2)}</pre>}
