import { beforeEach, describe, expect, it, vi } from "vitest";
import { MockBattleTransport } from "../transport/MockBattleTransport";
import { LocalBattleBotTransport } from "../bot/LocalBattleBotTransport";
import { DEFAULT_BATTLE_SYNC_CONFIG } from "../sync/InterpolationConfig";
import { RemoteBoardReplica } from "../sync/RemoteBoardReplica";
import type { BattleLocalBoard } from "./BattleLocalBoardRuntime";
import type { BattleBodyTransform, SpawnLetterEvent } from "../transport/battleTransportTypes";
import type { LocalBoardPublisher } from "../sync/LocalBoardPublisher";
import { BattleController } from "./BattleController";
import type { SignRecognizer } from "../../../recognition/core/SignRecognizer";

class FakeBoard implements BattleLocalBoard {
  starts = 0; stops = 0; spawns: SpawnLetterEvent[] = []; restored: (readonly BattleBodyTransform[])[] = []; accepted: string[] = []; rejected: (string | undefined)[] = []; selected: string | null = "letter-1"; disposed = false; gameOverHandler: (() => void) | null = null;
  start() { this.starts += 1; } stop() { this.stops += 1; } spawn(event: SpawnLetterEvent) { this.spawns.push(event); } selectRemoval() { return this.selected; }
  acceptRemoval(id: string) { this.accepted.push(id); } rejectRemoval(id?: string) { this.rejected.push(id); } removeLetter(id: string) { this.accepted.push(id); return true; } restore(bodies: readonly BattleBodyTransform[]) { this.restored.push(bodies); } getTargetSymbol() { return null; } takeTargetForOtter() { return null; } takeLetterForOtter(id: string) { this.accepted.push(id); return "ㅁ"; } resize() {} setPublisher(_publisher: LocalBoardPublisher) {} setGameOverHandler(handler: () => void) { this.gameOverHandler = handler; } dispose() { this.disposed = true; }
}
const attack = () => ({ apply: vi.fn(), dispose: vi.fn() });
const start = { type: "MATCH_STARTED" as const, sequence: 1, matchId: "m", roomId: "r", playerIds: ["me", "other"], startAt: 2000, serverTime: 1000 };
const spawn = (playerId: string): SpawnLetterEvent => ({ type: "SPAWN_LETTER", sequence: 2, matchId: "m", playerId, letterId: `letter-${playerId}`, spawnIndex: 0, symbol: "ㄱ", spawnAt: 2000, normalizedX: .5, initialAngle: 0 });

describe("BattleController", () => {
  beforeEach(() => vi.useFakeTimers());
  it("starts at the server startAt, not message receipt", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = new BattleController({ playerId: "me", roomId: "r", transport: t, localBoard: b, remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack() }); await c.connect({ url: "ws://x", roomId: "r", playerId: "me" }); t.emit(start); expect(c.snapshot().state).toBe("COUNTDOWN"); expect(b.starts).toBe(0); vi.advanceTimersByTime(999); expect(b.starts).toBe(0); vi.advanceTimersByTime(1); expect(b.starts).toBe(1); c.dispose(); });
  it("restores a running match only after its own authoritative board arrives", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const started = vi.fn(); const c = new BattleController({ playerId: "me", roomId: "r", transport: t, localBoard: b, remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack(), onMatchStarted: started }); await c.connect({ url: "ws://x", roomId: "r", playerId: "me" }); t.emit({ ...start, resume: true, resumePlayerId: "me", playerStates: [{ playerId: "me", score: 240, combo: 3, maxCombo: 5, removedCount: 4, gameOver: false }] }); expect(c.snapshot()).toMatchObject({ state: "RECONNECTING", countdownMs: 0, score: 240, combo: 3, maxCombo: 5, removedCount: 4 }); expect(b.starts).toBe(0); t.emit({ type: "BOARD_SNAPSHOT", sequence: 2, matchId: "m", playerId: "me", sentAt: 2_000, bodies: [snapshotBody("mine", .42)], restoreForPlayerId: "me" }); expect(c.snapshot().state).toBe("PLAYING"); expect(b.restored[0]).toEqual([expect.objectContaining({ id: "mine", y: .42 })]); expect(b.starts).toBe(1); expect(started).toHaveBeenCalledWith("m"); c.dispose(); });
  it("restores the current shared target atomically with a running match", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await connected(t, b); t.emit({ ...start, resume: true, resumePlayerId: "me", sharedTarget: { targetId: "target-7", symbol: "ㄱ", presentedAt: 2_000 } }); t.emit({ type: "BOARD_SNAPSHOT", sequence: 2, matchId: "m", playerId: "me", sentAt: 2_000, bodies: [], restoreForPlayerId: "me" }); expect(c.snapshot()).toMatchObject({ state: "PLAYING", targetSymbol: "ㄱ" }); c.dispose(); });
  it("does not rewind the player who stayed connected with another player's recovery snapshots", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.emit({ ...start, sequence: 20, resume: true, resumePlayerId: "other", playerStates: [{ playerId: "me", score: 0, combo: 0, maxCombo: 0, removedCount: 0, gameOver: false }] }); t.emit({ type: "BOARD_SNAPSHOT", sequence: 21, matchId: "m", playerId: "me", sentAt: 2_000, bodies: [], restoreForPlayerId: "other" }); expect(c.snapshot().state).toBe("PLAYING"); expect(b.starts).toBe(1); expect(b.stops).toBe(0); expect(b.restored).toHaveLength(0); c.dispose(); });
  it("waits for the reconnecting player's own field when the opponent field arrives first", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await connected(t, b); t.emit({ ...start, resume: true, resumePlayerId: "me" }); t.emit({ type: "BOARD_SNAPSHOT", sequence: 2, matchId: "m", playerId: "other", sentAt: 2_000, bodies: [snapshotBody("other-live", .56)], restoreForPlayerId: "me" }); expect(c.snapshot().state).toBe("RECONNECTING"); expect(b.starts).toBe(0); t.emit({ type: "BOARD_SNAPSHOT", sequence: 3, matchId: "m", playerId: "me", sentAt: 2_000, bodies: [], restoreForPlayerId: "me" }); expect(c.snapshot().state).toBe("PLAYING"); expect(b.starts).toBe(1); c.dispose(); });
  it("keeps an early match start received while the recognizer is connecting", async () => {
    const t = new MockBattleTransport(); const b = new FakeBoard(); let finishRecognizer!: () => void;
    const recognizer: SignRecognizer = { connect: () => new Promise<void>((resolve) => { finishRecognizer = resolve; }), disconnect() {}, subscribe: () => () => {}, getSupportedSymbols: () => [], getConnectionState: () => "CONNECTING" };
    const c = new BattleController({ playerId: "me", roomId: "r", transport: t, localBoard: b, remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack(), recognizer });
    const connecting = c.connect({ url: "ws://x", roomId: "r", playerId: "me" });
    t.emit(start); expect(c.snapshot().state).toBe("COUNTDOWN");
    finishRecognizer(); await connecting; expect(c.snapshot().state).toBe("COUNTDOWN");
    vi.advanceTimersByTime(1000); expect(c.snapshot().state).toBe("PLAYING"); expect(b.starts).toBe(1); c.dispose();
  });
  it("continues the match when the optional recognizer connection fails", async () => {
    const t = new MockBattleTransport(); const b = new FakeBoard();
    const recognizer: SignRecognizer = { connect: () => Promise.reject(new Error("AI offline")), disconnect() {}, subscribe: () => () => {}, getSupportedSymbols: () => [], getConnectionState: () => "ERROR" };
    const c = new BattleController({ playerId: "me", roomId: "r", transport: t, localBoard: b, remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack(), recognizer });
    await c.connect({ url: "ws://x", roomId: "r", playerId: "me" }); expect(c.snapshot().state).toBe("WAITING_START");
    t.emit(start); vi.advanceTimersByTime(1000); expect(c.snapshot().state).toBe("PLAYING"); expect(b.starts).toBe(1); c.dispose();
  });
  it("starts local bot practice even while the recognizer remains unavailable", async () => {
    const b = new FakeBoard(); const t = new LocalBattleBotTransport();
    const recognizer: SignRecognizer = { connect: () => new Promise<void>(() => undefined), disconnect() {}, subscribe: () => () => {}, getSupportedSymbols: () => [], getConnectionState: () => "CONNECTING" };
    const c = new BattleController({ playerId: "me", roomId: "block-bot-practice", transport: t, localBoard: b, remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack(), recognizer });
    void c.connect({ url: "local://block-bot", roomId: "block-bot-practice", playerId: "me" });
    vi.advanceTimersByTime(50); expect(c.snapshot().state).toBe("PLAYING"); expect(c.snapshot().countdownMs).toBe(0); expect(b.starts).toBe(1); c.dispose();
  });
  it("spawns only server-issued local letters", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await connected(t, b); t.emit(spawn("other")); t.emit(spawn("me")); expect(b.spawns.map((e) => e.playerId)).toEqual(["me"]); c.dispose(); });
  it("waits for the shared claim effect before spawning the winner letter", async () => {
    const t = new MockBattleTransport(); const b = new FakeBoard();
    const c = new BattleController({ playerId: "me", roomId: "r", transport: t, localBoard: b, remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack(), now: () => 1_000 });
    await c.connect({ url: "ws://x", roomId: "r", playerId: "me" });
    t.emit({ ...spawn("me"), spawnAt: 2_150 });
    expect(b.spawns).toHaveLength(0);
    vi.advanceTimersByTime(1_149);
    expect(b.spawns).toHaveLength(0);
    vi.advanceTimersByTime(1);
    expect(b.spawns).toHaveLength(1);
    c.dispose();
  });
  it("claims the shared target without spawning optimistically", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); expect(c.submitRecognizedSymbol("ㄱ", .9)).toBe(true); expect(t.sent.at(-1)?.type).toBe("CLAIM_SHARED_TARGET"); expect(b.spawns).toHaveLength(0); c.dispose(); });
  it("removes only after server acceptance and uses official score", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); c.submitRecognizedSymbol("ㄱ"); t.emit({ type: "REMOVE_LETTER_ACCEPTED", sequence: 3, playerId: "me", letterId: "letter-1", symbol: "ㄱ", score: 300, combo: 2, maxCombo: 4, removedCount: 3, acceptedAt: Date.now() }); expect(b.accepted).toEqual(["letter-1"]); expect(c.snapshot()).toMatchObject({ score: 300, combo: 2, maxCombo: 4, removedCount: 3 }); c.dispose(); });
  it("releases a pending target after rejection", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.emit({ type: "REMOVE_LETTER_REJECTED", sequence: 4, letterId: "letter-1", code: "MISMATCH", message: "symbol mismatch", rejectedAt: Date.now() }); expect(b.rejected).toEqual(["letter-1"]); expect(c.snapshot().message).toBe("symbol mismatch"); c.dispose(); });
  it("does not reset the combo after a wrong shared-target answer", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); expect(c.submitRecognizedSymbol("ㅅ")).toBe(false); expect(t.sent.some((message) => message.type === "RESET_COMBO_COMMAND")).toBe(false); c.dispose(); });
  it("ignores the previous confirmed sign while a new shared target settles", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.emit({ type: "SHARED_TARGET", sequence: 3, matchId: "m", targetId: "target-2", symbol: "ㄴ", presentedAt: Date.now() }); expect(c.submitRecognizedSymbol("ㄱ")).toBe(false); expect(t.sent.some((message) => message.type === "RESET_COMBO_COMMAND")).toBe(false); expect(c.submitRecognizedSymbol("ㄴ")).toBe(true); expect(t.sent.at(-1)).toMatchObject({ type: "CLAIM_SHARED_TARGET", targetId: "target-2", symbol: "ㄴ" }); c.dispose(); });
  it("tracks both combo meters from one authoritative event stream", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const updated = vi.fn(); const c = new BattleController({ playerId: "me", roomId: "r", transport: t, localBoard: b, remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack(), sharedTargetMode: true, onComboUpdated: updated }); await c.connect({ url: "ws://x", roomId: "r", playerId: "me" }); t.emit({ type: "COMBO_UPDATED", sequence: 3, playerId: "me", combo: 2, maxCombo: 2, reason: "CORRECT" }); t.emit({ type: "COMBO_UPDATED", sequence: 4, playerId: "other", combo: 1, maxCombo: 1, reason: "CORRECT" }); expect(c.snapshot()).toMatchObject({ combo: 2, opponentCombo: 1, maxCombo: 2 }); expect(updated).toHaveBeenCalledTimes(2); c.dispose(); });
  it("keeps the winner combo from the claimed target event even when a combo event is delayed", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.emit({ type: "SHARED_TARGET_CLAIMED", sequence: 4, matchId: "m", targetId: "target-1", winnerPlayerId: "me", symbol: "ㄱ", score: 220, combo: 2, maxCombo: 2, removedCount: 2, acceptedAt: Date.now() }); expect(c.snapshot()).toMatchObject({ combo: 2, maxCombo: 2, score: 220, removedCount: 2 }); c.dispose(); });
  it("removes the hammer victim at impact and spawns it on the attacker board", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const remote = new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG); const removeRemote = vi.spyOn(remote, "removeLetter"); const attacked = vi.fn(); const c = new BattleController({ playerId: "me", roomId: "r", transport: t, localBoard: b, remoteBoard: remote, attackEffect: attack(), sharedTargetMode: true, now: () => 1_000, onHammerAttack: attacked }); await c.connect({ url: "ws://x", roomId: "r", playerId: "me" }); t.emit({ type: "HAMMER_ATTACK", sequence: 9, matchId: "m", attackId: "hammer-1", attackerPlayerId: "me", defenderPlayerId: "other", sourceCombo: 3, victimLetterId: "other-bottom", transferredLetterId: "me-hammer-letter", symbol: "ㅁ", sourceNormalizedX: .4, sourceNormalizedY: .82, createdAt: 1_000, impactAt: 1_300, spawnAt: 1_700 }); expect(attacked).toHaveBeenCalledOnce(); await vi.advanceTimersByTimeAsync(299); expect(removeRemote).not.toHaveBeenCalled(); await vi.advanceTimersByTimeAsync(1); expect(removeRemote).toHaveBeenCalledWith("other-bottom"); await vi.advanceTimersByTimeAsync(400); expect(b.spawns).toContainEqual(expect.objectContaining({ playerId: "me", letterId: "me-hammer-letter", symbol: "ㅁ" })); c.dispose(); });
  it("applies attacks only when the local player is target", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const effect = attack(); const c = await connected(t, b, effect); const event = { type: "ATTACK_CREATED" as const, sequence: 5, attackId: "a", attackerPlayerId: "other", targetPlayerId: "me", attackType: "PUSH", amount: 1, sourceCombo: 3, createdAt: Date.now() }; t.emit(event); expect(effect.apply).toHaveBeenCalledOnce(); t.emit({ ...event, sequence: 6, targetPlayerId: "other" }); expect(effect.apply).toHaveBeenCalledOnce(); c.dispose(); });
  it("cleans transport, board and effects", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const effect = attack(); const c = await connected(t, b, effect); c.dispose(); expect(t.getConnectionState()).toBe("DISCONNECTED"); expect(b.disposed).toBe(true); expect(effect.dispose).toHaveBeenCalledOnce(); });
  it("keeps the remaining player live without requesting a rewind after its channel reconnects", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.simulateConnectionState("DISCONNECTED"); expect(c.snapshot().state).toBe("PLAYING"); expect(b.stops).toBe(0); await vi.advanceTimersByTimeAsync(1000); expect(t.connections).toHaveLength(2); expect(t.sent.some((message) => message.type === "PLAYER_RECONNECTED" || message.type === "REQUEST_MATCH_STATE")).toBe(false); c.dispose(); });
  it("returns the remaining browser's latest interpolated opponent board after reconnection", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.emit({ type: "BOARD_SNAPSHOT", sequence: 12, matchId: "m", playerId: "other", sentAt: 500, bodies: [{ id: "other-1", symbol: "ㄱ", x: .5, y: .4, angle: 0, velocityX: 0, velocityY: 2, angularVelocity: 0, state: "FALLING" }] }); t.simulateConnectionState("DISCONNECTED"); await vi.advanceTimersByTimeAsync(1_000); expect(t.sent).toContainEqual(expect.objectContaining({ type: "PEER_BOARD_VIEW", observerPlayerId: "me", subjectPlayerId: "other", sentAt: expect.any(Number), bodies: [expect.objectContaining({ id: "other-1", x: .5, y: .4 })] })); c.dispose(); });
  it("keeps play active while a fresh opponent snapshot arrives", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.simulateConnectionState("DISCONNECTED"); await vi.advanceTimersByTimeAsync(1000); t.emit({ type: "BOARD_SNAPSHOT", sequence: 20, matchId: "m", playerId: "other", sentAt: Date.now(), bodies: [] }); expect(c.snapshot().state).toBe("PLAYING"); expect(b.starts).toBe(1); c.dispose(); });
  it("does not invent a winner from an ambiguous local transport drop", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.simulateConnectionState("DISCONNECTED"); await vi.advanceTimersByTimeAsync(10_000); expect(c.snapshot()).toMatchObject({ state: "PLAYING", result: null }); expect(b.stops).toBe(0); c.dispose(); });
  it("awards the remaining player after an identified opponent disconnect exceeds grace", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.emit({ type: "PLAYER_DISCONNECTED", sequence: 30, playerId: "other" }); await vi.advanceTimersByTimeAsync(10_000); expect(c.snapshot()).toMatchObject({ state: "FINISHED", result: expect.objectContaining({ winnerPlayerId: "me", loserPlayerId: "other", reason: "RECONNECT_TIMEOUT" }) }); expect(b.stops).toBe(1); c.dispose(); });
  it("keeps the match running when the opponent reconnects within grace", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.simulateConnectionState("DISCONNECTED"); await vi.advanceTimersByTimeAsync(1_000); t.emit({ type: "BOARD_SNAPSHOT", sequence: 20, matchId: "m", playerId: "other", sentAt: Date.now(), bodies: [] }); await vi.advanceTimersByTimeAsync(10_000); expect(c.snapshot()).toMatchObject({ state: "PLAYING", result: null }); c.dispose(); });
  it("cancels the leave timeout when the same match resumes", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.simulateConnectionState("DISCONNECTED"); t.emit({ ...start, matchId: "m", resume: true, resumePlayerId: "me", playerStates: [{ playerId: "me", score: 0, combo: 0, maxCombo: 0, removedCount: 0, gameOver: false }] }); t.emit({ type: "BOARD_SNAPSHOT", sequence: 21, matchId: "m", playerId: "me", sentAt: Date.now(), bodies: [], restoreForPlayerId: "me" }); await vi.advanceTimersByTimeAsync(10_000); expect(c.snapshot()).toMatchObject({ state: "PLAYING", result: null }); c.dispose(); });
  it("uses MATCH_FINISHED as the final result", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); t.emit({ type: "MATCH_FINISHED", sequence: 30, matchId: "m", winnerPlayerId: "other", loserPlayerId: "me", reason: "RECONNECT_TIMEOUT", finishedAt: Date.now(), results: [{ playerId: "me", score: 100, maxCombo: 2, removedCount: 1, attackCount: 0 }] }); expect(c.snapshot().state).toBe("FINISHED"); expect(c.snapshot().result?.winnerPlayerId).toBe("other"); c.dispose(); });
  it("keeps the final result when a late resume snapshot arrives", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); const result = { type: "MATCH_FINISHED" as const, sequence: 30, matchId: "m", winnerPlayerId: "me", loserPlayerId: "other", reason: "DANGER_LINE", finishedAt: Date.now() }; t.emit(result); t.emit({ ...start, sequence: 31, resume: true, startAt: Date.now(), serverTime: Date.now() }); expect(c.snapshot()).toMatchObject({ state: "FINISHED", result: expect.objectContaining({ winnerPlayerId: "me", loserPlayerId: "other" }) }); expect(b.starts).toBe(1); c.dispose(); });
  it("reports local danger-line game over exactly once", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); b.gameOverHandler?.(); b.gameOverHandler?.(); expect(t.sent.filter((message) => message.type === "PLAYER_GAME_OVER_COMMAND")).toHaveLength(1); c.dispose(); });
  it("sends an authoritative forfeit while a match is playing", async () => { const t = new MockBattleTransport(); const b = new FakeBoard(); const c = await playing(t, b); expect(c.forfeit()).toBe(true); expect(t.sent.at(-1)).toMatchObject({ type: "PLAYER_FORFEIT_COMMAND", matchId: "m" }); c.dispose(); });
  it("uses a fresh match id and reset state for rematch", async () => { const ids: string[] = []; const firstTransport = new MockBattleTransport(); const first = new BattleController({ playerId: "me", roomId: "r", transport: firstTransport, localBoard: new FakeBoard(), remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack(), onMatchStarted: (id) => ids.push(id) }); await first.connect({ url: "ws://x", roomId: "r", playerId: "me" }); firstTransport.emit({ ...start, matchId: "match-1" }); first.dispose(); const secondTransport = new MockBattleTransport(); const second = new BattleController({ playerId: "me", roomId: "r", transport: secondTransport, localBoard: new FakeBoard(), remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: attack(), onMatchStarted: (id) => ids.push(id) }); await second.connect({ url: "ws://x", roomId: "r", playerId: "me" }); secondTransport.emit({ ...start, matchId: "match-2" }); expect(ids).toEqual(["match-1", "match-2"]); expect(second.snapshot()).toMatchObject({ score: 0, combo: 0, removedCount: 0, result: null }); second.dispose(); });
});

async function connected(t: MockBattleTransport, b: FakeBoard, effect = attack()) { const c = new BattleController({ playerId: "me", roomId: "r", transport: t, localBoard: b, remoteBoard: new RemoteBoardReplica(DEFAULT_BATTLE_SYNC_CONFIG), attackEffect: effect, sharedTargetMode: true, createCommandId: () => "cmd" }); await c.connect({ url: "ws://x", roomId: "r", playerId: "me" }); return c; }
async function playing(t: MockBattleTransport, b: FakeBoard) { const c = await connected(t, b); t.emit({ ...start, startAt: 1000, serverTime: 1000 }); vi.runOnlyPendingTimers(); t.emit({ type: "SHARED_TARGET", sequence: 2, matchId: "m", targetId: "target-1", symbol: "ㄱ", presentedAt: Date.now() }); return c; }
function snapshotBody(id: string, y: number): BattleBodyTransform { return { id, symbol: "ㄱ", x: .5, y, angle: 0, velocityX: 0, velocityY: 2, angularVelocity: 0, state: "FALLING" }; }

