import {describe,expect,it,vi} from "vitest";import type {LineRaceMatchSnapshot,LineRaceServerEvent,LineRaceMatchConfig} from "../contracts";import {NetworkLineRaceController} from "./NetworkLineRaceController";import type {LineRaceServerClock} from "./LineRaceServerClock";
const match="40000000-0000-4000-8000-000000000001",me="10000000-0000-4000-8000-000000000001",other="20000000-0000-4000-8000-000000000001",obstacleId="50000000-0000-4000-8000-000000000001";const config:LineRaceMatchConfig={raceLength:1000,baseSpeedPerSecond:100,matchDurationMs:60000,countdownMs:3000,handSize:3,attackCooldownMs:900,counterWindowMs:2500,obstacleLeadDistance:150,minimumObstacleSpacing:80,maxPendingObstacles:6,reconnectGraceMs:10000,supportedSymbols:["ㄱ","ㄴ"]};
class Clock implements LineRaceServerClock{value=1000;updateOffset(){}now(){return this.value;}}
describe("NetworkLineRaceController",()=>{it("restores a non-empty private hand, player names, progress and active obstacles from snapshot",()=>{const clock=new Clock(),controller=new NetworkLineRaceController(match,me,clock,undefined,[{playerId:me,displayName:"민수"},{playerId:other,displayName:"지수"}]);controller.connect();controller.applySnapshot(snapshot());const view=controller.getView();expect(view.clientState).toBe("PLAYING");expect(view.hand).toEqual(["ㄱ","ㄴ","ㄱ"]);expect(view.hand.length).toBeGreaterThan(0);expect(view.render.players[0]).toMatchObject({playerId:"PLAYER_A",displayName:"민수 (나)"});expect(view.render.players[1]?.displayName).toBe("지수 (상대)");expect(view.render.obstacles).toHaveLength(1);expect(view.render.obstacles[0]?.targetPlayerId).toBe("PLAYER_A");});
it("ignores duplicate sequence and finishes only from the server finish event",()=>{const clock=new Clock(),gap=vi.fn(),controller=new NetworkLineRaceController(match,me,clock,gap);controller.connect();controller.applySnapshot(snapshot());const progress=event("LINE_RACE_PROGRESS_UPDATED",12,{serverTime:1100,players:[{playerId:me,progress:300,accumulatedPenaltyMs:0,state:"RUNNING"},{playerId:other,progress:250,accumulatedPenaltyMs:0,state:"RUNNING"}]});expect(controller.apply(progress)).toBe(true);expect(controller.apply(progress)).toBe(false);expect(controller.getView().clientState).toBe("PLAYING");controller.apply(event("LINE_RACE_MATCH_FINISHED",13,{roomId:"30000000-0000-4000-8000-000000000001",winnerPlayerId:me,loserPlayerId:other,finishReason:"FINISH_LINE",results:[],startedAt:0,finishedAt:1200}));expect(controller.getView().clientState).toBe("FINISHED");});
it("keeps counter failure obstacle and removes it only after success/removal event",()=>{const clock=new Clock(),controller=new NetworkLineRaceController(match,me,clock);controller.connect();controller.applySnapshot(snapshot());controller.apply(event("LINE_RACE_COUNTER_FAILED",11,{commandId:"60000000-0000-4000-8000-000000000001",playerId:me,obstacleId,reason:"COUNTER_WINDOW_EXPIRED"}));expect(controller.getView().render.obstacles).toHaveLength(1);controller.apply(event("LINE_RACE_COUNTER_SUCCEEDED",12,{playerId:me,obstacleId,symbol:"ㄱ",counterAt:1200}));expect(controller.getView().render.obstacles[0]?.state).toBe("COUNTERED");});
it("pauses on disconnect and fully restores from the authoritative snapshot",()=>{const clock=new Clock(),controller=new NetworkLineRaceController(match,me,clock);controller.connect();controller.applySnapshot(snapshot());clock.value=20_000;controller.connectionLost();const paused=controller.getView();expect(paused.clientState).toBe("RECONNECTING");expect(paused.render.state).toBe("PAUSED");const remaining=paused.render.remainingMs;clock.value=30_000;expect(controller.getView().render.remainingMs).toBe(remaining);const restored={...snapshot(),serverTime:30_000,finishDeadlineAt:89_500,sequence:20,myAttackHand:["ㄴ"]};controller.applySnapshot(restored);expect(controller.getView().clientState).toBe("PLAYING");expect(controller.getView().hand).toEqual(["ㄴ"]);expect(controller.getView().render.remainingMs).toBeGreaterThan(0);});
it("never exposes PLAYING with zero remaining time and does not invent a winner",()=>{const clock=new Clock(),controller=new NetworkLineRaceController(match,me,clock);controller.connect();controller.applySnapshot(snapshot());clock.value=70_000;controller.tick();const view=controller.getView();expect(view.clientState).toBe("PLAYING");expect(view.render.remainingMs).toBe(1);expect(view.render.winnerPlayerId).toBeUndefined();});
it("ignores duplicate finish events even when their sequence differs",()=>{const clock=new Clock(),controller=new NetworkLineRaceController(match,me,clock);controller.connect();controller.applySnapshot(snapshot());const finished=event("LINE_RACE_MATCH_FINISHED",12,{roomId:"30000000-0000-4000-8000-000000000001",winnerPlayerId:me,loserPlayerId:other,finishReason:"TIME_LIMIT",results:[],startedAt:0,finishedAt:1200});expect(controller.apply(finished)).toBe(true);expect(controller.apply({...finished,sequence:13,eventId:"duplicate"} as LineRaceServerEvent)).toBe(false);expect(controller.getView().finished?.eventId).toBe(finished.eventId);});
it("restores an official result from a FINISHED snapshot",()=>{const clock=new Clock(),controller=new NetworkLineRaceController(match,me,clock);controller.connect();controller.applySnapshot({...snapshot(),status:"FINISHED",sequence:20,result:{matchId:match,roomId:"30000000-0000-4000-8000-000000000001",winnerPlayerId:me,loserPlayerId:other,finishReason:"TIME_LIMIT",results:[],startedAt:500,finishedAt:60_500}});expect(controller.getView().clientState).toBe("FINISHED");expect(controller.getView().finished?.winnerPlayerId).toBe(me);});
it("renders no runners or progress while server state is IDLE",()=>{const controller=new NetworkLineRaceController(match,me,new Clock());const view=controller.getView();expect(view.render.state).toBe("IDLE");expect(view.render.remainingMs).toBe(0);expect(view.render.players).toEqual([]);});
it("rejects a first PLAYING snapshot with an empty attack hand",()=>{const controller=new NetworkLineRaceController(match,me,new Clock());controller.connect();controller.applySnapshot({...snapshot(),myAttackHand:[]});const view=controller.getView();expect(view.clientState).toBe("ERROR");expect(view.hand).toEqual([]);expect(view.render.state).toBe("IDLE");expect(view.lastError).toMatch(/공격 패/);});
it("rejects a PLAYING snapshot whose deadline is not after server time",()=>{const controller=new NetworkLineRaceController(match,me,new Clock());controller.connect();controller.applySnapshot({...snapshot(),serverTime:60_500,finishDeadlineAt:60_500});const view=controller.getView();expect(view.clientState).toBe("ERROR");expect(view.render.remainingMs).toBe(0);expect(view.lastError).toMatch(/PLAYING 상태를 거부/);});
it("freezes authoritative final progress after FINISHED",()=>{const clock=new Clock(),controller=new NetworkLineRaceController(match,me,clock);controller.connect();controller.applySnapshot(snapshot());controller.apply(event("LINE_RACE_MATCH_FINISHED",12,{roomId:"30000000-0000-4000-8000-000000000001",winnerPlayerId:other,loserPlayerId:me,finishReason:"FINISH_LINE",results:[result(me,700),result(other,1000)],startedAt:500,finishedAt:1200}));const finished=controller.getView().render;clock.value=99_000;const later=controller.getView().render;expect(later.state).toBe("FINISHED");expect(later.players).toEqual(finished.players);expect(later.obstacles).toEqual([]);expect(later.simulationNow).toBe(finished.simulationNow);expect(later.remainingMs).toBe(0);});
it("renders COUNTDOWN and the private hand only after the first authoritative snapshot",()=>{const controller=new NetworkLineRaceController(match,me,new Clock());controller.connect();expect(controller.getView().synchronized).toBe(false);expect(controller.apply(event("LINE_RACE_OBSTACLE_CREATED",9,{obstacleId,obstacle:obstacle("ACTIVE")}))).toBe(false);controller.applySnapshot({...snapshot(),status:"COUNTDOWN",serverTime:1_000,startAt:2_000,finishDeadlineAt:62_000,obstacles:[],sequence:10});const view=controller.getView();expect(view.synchronized).toBe(true);expect(view.clientState).toBe("COUNTDOWN");expect(view.render.state).toBe("COUNTDOWN");expect(view.render.players).toHaveLength(2);expect(view.hand.length).toBeGreaterThan(0);expect(view.render.obstacles).toEqual([]);});
it("shows a start synchronization error for a WAITING first snapshot",()=>{const controller=new NetworkLineRaceController(match,me,new Clock());controller.connect();controller.applySnapshot({...snapshot(),status:"WAITING",myAttackHand:[]});const view=controller.getView();expect(view.synchronized).toBe(false);expect(view.clientState).toBe("ERROR");expect(view.render.state).toBe("IDLE");expect(view.lastError).toMatch(/경기 시작 동기화 오류/);});
});
function snapshot():LineRaceMatchSnapshot{return{matchId:match,roomId:"30000000-0000-4000-8000-000000000001",status:"PLAYING",serverTime:1000,startAt:500,finishDeadlineAt:60500,config,myAttackHand:["ㄱ","ㄴ","ㄱ"],sequence:10,players:[{playerId:me,progress:100,score:0,combo:2,maxCombo:2,pendingObstacleIds:[obstacleId],accumulatedPenaltyMs:0,connected:true,state:"RUNNING"},{playerId:other,progress:90,score:0,combo:0,maxCombo:0,pendingObstacleIds:[],accumulatedPenaltyMs:0,connected:true,state:"RUNNING"}],obstacles:[obstacle("ACTIVE"),{...obstacle("TRAVERSED"),obstacleId:"50000000-0000-4000-8000-000000000002"}]};}
function obstacle(status:"ACTIVE"|"TRAVERSED"){return{obstacleId,templateId:"jamo-giyeok",symbol:"ㄱ",attackerPlayerId:other,targetPlayerId:me,coursePosition:300,penaltyMs:1000,createdAt:0,warningEndsAt:500,counterDeadlineAt:2000,status};}
function event(type:string,sequence:number,payload:Record<string,unknown>){return{type,eventId:`70000000-0000-4000-8000-${String(sequence).padStart(12,"0")}`,matchId:match,sequence,occurredAt:1000,...payload} as LineRaceServerEvent;}
function result(playerId:string,finalProgress:number){return{playerId,finalProgress,attacksAttempted:0,attacksAccepted:0,countersAttempted:0,countersSucceeded:0,obstaclesTraversed:0,accumulatedPenaltyMs:0,maxCombo:0,averageRecognitionMs:0,symbolStatistics:[]};}
